name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
- name: exec-javascriptdiagnostic
  # You may pin to the exact commit or the version.
  # uses: steiley/exec-javascript-diagnostic@edceb50f9c067ee6183592d83fd802c728703a26
  uses: steiley/exec-javascript-diagnostic@v0.0.2
  with:
    # Name of package to execute
    package_name: 
    # Target Path to execute
    target_path: 
    # Execute command name
    execute_command: # optional
    
  - name: Flarum Extension JavaScript Build - Yarn
  # You may pin to the exact commit or the version.
  # uses: davwheat/action-build-flarum-ext-js-yarn@eecc5f51419843ab74aadeee77efb310676fd716
  uses: davwheat/action-build-flarum-ext-js-yarn@v1.0.0
  
  - name: aws-cdk-js-github-action
  # You may pin to the exact commit or the version.
  # uses: MikeBild/aws-cdk-js-github-action@a6be403fbbbf6a1ecdc71744ee1712e98ad54ff2
  uses: MikeBild/aws-cdk-js-github-action@1.0.0
  
  
    
  
